"""
Plot query-awareness trend results for Q1–Q8 only.

Assumes results have already been generated by test_player_query_awareness_trend.py
(i.e. results/player_query_awareness_trend/run/trend_metrics.json exists).
Reads that file, filters to Q1–Q8, and writes plots to the same run/plots directory.
"""

import json
import sys
from pathlib import Path

try:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
except ImportError:
    print("matplotlib not available - install it to generate plots")
    sys.exit(1)

# Paths (match test_player_query_awareness_trend.py)
SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent.parent
RESULTS_DIR = PROJECT_ROOT / "results"
RUN_DIR = RESULTS_DIR / "player_query_awareness_trend" / "run"
PLOTS_DIR = RUN_DIR / "plots"
METRICS_JSON = RUN_DIR / "trend_metrics.json"

Q_MIN, Q_MAX = 1, 8  # Plot Q1 through Q8 (but exclude Q4)
EXCLUDE_QUERIES = {'Q4'}  # Exclude Q4 from the plots


def get_similarity_order() -> dict:
    """
    Map query_id to reordering position based on actual training workload similarity.
    
    Empirically determined from training join queries:
    - Most similar (flat high): Q1, Q2, Q3 (all binary player⟕team, 100% familiar)
    - Medium: Q8 (3-table but has unfamiliar columns)
    - Q4 separately (team anchor instead of player)
    - Q5-Q7 (3-table player⟕team⟕city, all familiar)
    
    Reordered: Q1, Q2, Q3, Q4, Q5, Q6, Q7, Q8
    (Already in order, but we compute scores to show the logic)
    """
    # Similarity scores (higher = more aligned with training)
    scores = {
        'Q1': 1.00,   # binary player⟕team, all familiar
        'Q2': 1.00,   # binary player⟕team, all familiar
        'Q3': 1.00,   # binary player⟕team, all familiar
        'Q4': 0.70,   # team anchor (rare in training)
        'Q5': 0.95,   # 3-table but all familiar columns
        'Q6': 0.95,   # 3-table but all familiar columns
        'Q7': 0.95,   # 3-table but all familiar columns
        'Q8': 0.80,   # 3-table but has unfamiliar columns (city.area, player.birth_date)
    }
    return scores


def load_metrics() -> list:
    """Load trend metrics from JSON; return list of dicts for Q1..Q8 (except Q4), sorted by similarity."""
    if not METRICS_JSON.exists():
        print(f"Metrics file not found: {METRICS_JSON}")
        print("Run test_player_query_awareness_trend.py first to generate results.")
        sys.exit(1)

    with open(METRICS_JSON) as f:
        all_rows = json.load(f)

    filtered = [
        r for r in all_rows
        if r.get("query_id") and r["query_id"].startswith("Q")
        and Q_MIN <= int(r["query_id"][1:]) <= Q_MAX
        and r["query_id"] not in EXCLUDE_QUERIES
    ]
    
    # Sort by training similarity (descending: most similar first)
    scores = get_similarity_order()
    filtered.sort(key=lambda r: -scores.get(r["query_id"], 0))
    return filtered


def main() -> int:
    metrics = load_metrics()
    if not metrics:
        print(f"No metrics found for Q{Q_MIN}–Q{Q_MAX}. Check {METRICS_JSON}")
        return 1

    # Print reordering info
    print("Query order (most to least aligned with training workload):")
    print("=" * 60)
    for i, m in enumerate(metrics, 1):
        actual_qid = m["query_id"]
        f1 = m["macro_f1"]
        print(f"  Q{i} (actual: {actual_qid}): F1={f1:.3f}")
    print()

    PLOTS_DIR.mkdir(parents=True, exist_ok=True)

    # Create display labels (Q1, Q2, Q3, Q4, Q5, Q6, Q7 - skipping Q4 position)
    x_labels = [f"Q{i}" for i in range(1, len(metrics) + 1)]
    x = list(range(len(x_labels)))
    result_rows = [m["result_rows"] for m in metrics]
    token_cost = [m["total_tokens"] for m in metrics]
    latency = [m["latency_s"] for m in metrics]
    f1 = [m["macro_f1"] for m in metrics]
    precision = [m["macro_precision"] for m in metrics]
    recall = [m["macro_recall"] for m in metrics]

    # 2x2 summary
    fig, axes = plt.subplots(2, 2, figsize=(12, 9))
    fig.suptitle(
        "Player Query-Awareness Trend\n"
        "(Left: most aligned with training workload → Right: least aligned)",
        fontsize=14, fontweight="bold"
    )

    axes[0, 0].plot(x, result_rows, marker="o", color="#7f8c8d")
    axes[0, 0].set_title("Result Table Size (rows)")
    axes[0, 0].set_xticks(x)
    axes[0, 0].set_xticklabels(x_labels)
    axes[0, 0].set_ylabel("rows")
    axes[0, 0].grid(alpha=0.3)

    axes[0, 1].plot(x, token_cost, marker="o", color="#8e44ad")
    axes[0, 1].set_title("Token Cost (estimated total tokens)")
    axes[0, 1].set_xticks(x)
    axes[0, 1].set_xticklabels(x_labels)
    axes[0, 1].set_ylabel("tokens")
    axes[0, 1].grid(alpha=0.3)

    axes[1, 0].plot(x, latency, marker="o", color="#2980b9")
    axes[1, 0].set_title("Latency")
    axes[1, 0].set_xticks(x)
    axes[1, 0].set_xticklabels(x_labels)
    axes[1, 0].set_ylabel("seconds")
    axes[1, 0].grid(alpha=0.3)

    axes[1, 1].plot(x, f1, marker="o", color="#27ae60")
    axes[1, 1].set_title("Macro F1 (official evaluator)")
    axes[1, 1].set_xticks(x)
    axes[1, 1].set_xticklabels(x_labels)
    axes[1, 1].set_ylim(0.0, 1.0)
    axes[1, 1].set_ylabel("F1")
    axes[1, 1].grid(alpha=0.3)

    plt.tight_layout()
    summary_path = PLOTS_DIR / "query_awareness_trend_q1_q8_summary.png"
    plt.savefig(summary_path, dpi=300, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved: {summary_path}")

    # F1-only plot
    fig2, ax2 = plt.subplots(figsize=(10, 5))
    ax2.plot(x, f1, marker="o", color="#27ae60", linewidth=2, markersize=8, label="F1")
    ax2.set_xticks(x)
    ax2.set_xticklabels(x_labels)
    ax2.set_ylim(0.0, 1.0)
    ax2.set_title("Macro F1 Score")
    ax2.set_xlabel("Query (left: most aligned with training workload → right: least aligned)")
    ax2.set_ylabel("F1")
    ax2.grid(alpha=0.3)
    ax2.legend()
    plt.tight_layout()
    f1_path = PLOTS_DIR / "query_awareness_trend_q1_q8_f1.png"
    plt.savefig(f1_path, dpi=300, bbox_inches="tight")
    plt.close(fig2)
    print(f"Saved: {f1_path}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
